### ISSUE TITLE
Suunnittele ulkoasu template

### ISSUE THREAD

**Issue by junttip** [junttip/karttademo#1]
Suunnitelma minkä näköinen perus sivu on tietokoneen selaimella.

**Comment by ArttuHosio1** [comment]
Ulkoasu sivustolle
Kesto noin 15min

**Comment by junttip** [comment]
Uusia visioita:
tehdään lista tapahtumista:
- portaat
- bingo
- buffet
- info
- jne.

Ja aina kun listaa klikkaa tietty kartan alue vaihtaa väriä
