### ISSUE TITLE
Kartta klikkausvärit kuntoon

### ISSUE THREAD

**Issue by junttip** [junttip/karttademo#23]
Korjataan klikkausvärit:
- Harmaa: Huoneessa ei ole mitään aktiviteetteja
- Beetroot: Huoneessa on aktiviteetti
- Honey: Käyttäjä on klikannut huonetta ja sivusto näyttää huoneen aktiviteetin tiedot

**Comment by ArttuHosio1** [comment]
Noin 2-3 tuntia
